# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from PyQt5 import QtCore,QtWidgets
from PyQt5.QtWidgets import QFileDialog
from smtptools import Smtp
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(612, 522)
        MainWindow.setMinimumSize(QtCore.QSize(612, 515))
        MainWindow.setMaximumSize(QtCore.QSize(612, 515))
        MainWindow.setBaseSize(QtCore.QSize(612, 515))
        MainWindow.setWindowIcon(QIcon("./01.ico"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 594, 457))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_toaddr = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_toaddr.setMinimumSize(QtCore.QSize(511, 31))
        self.lineEdit_toaddr.setMaximumSize(QtCore.QSize(511, 31))
        self.lineEdit_toaddr.setObjectName("lineEdit_toaddr")
        self.horizontalLayout.addWidget(self.lineEdit_toaddr)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_title = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_title.setMinimumSize(QtCore.QSize(511, 31))
        self.lineEdit_title.setMaximumSize(QtCore.QSize(511, 31))
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.horizontalLayout_2.addWidget(self.lineEdit_title)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.msgbox = QtWidgets.QTextEdit(self.layoutWidget)
        self.msgbox.setMinimumSize(QtCore.QSize(581, 281))
        self.msgbox.setMaximumSize(QtCore.QSize(581, 281))
        self.msgbox.setObjectName("msgbox")
        self.verticalLayout.addWidget(self.msgbox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.addfile_button = QtWidgets.QPushButton(self.layoutWidget)
        self.addfile_button.setMinimumSize(QtCore.QSize(171, 28))
        self.addfile_button.setMaximumSize(QtCore.QSize(171, 28))
        self.addfile_button.setObjectName("addfile_button")
        self.horizontalLayout_3.addWidget(self.addfile_button)
        self.send_button = QtWidgets.QPushButton(self.layoutWidget)
        self.send_button.setMinimumSize(QtCore.QSize(171, 28))
        self.send_button.setMaximumSize(QtCore.QSize(171, 28))
        self.send_button.setObjectName("send_button")
        self.horizontalLayout_3.addWidget(self.send_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 按钮绑定
        self.addfile_button.clicked.connect(self.addfile)
        self.send_button.clicked.connect(self.send)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SMTP邮件发送"))
        self.label.setText(_translate("MainWindow", "收件人:"))
        self.label_2.setText(_translate("MainWindow", "主  题："))
        self.label_3.setText(_translate("MainWindow", "内  容:"))
        self.label_4.setText(_translate("MainWindow", "designed by ZB666"))
        self.addfile_button.setText(_translate("MainWindow", "添加附件"))
        self.send_button.setText(_translate("MainWindow", "发送"))
        self.filename = None

    ###########  按钮函数  ############
    def send(self):
        to_addr = self.lineEdit_toaddr.text()
        title = self.lineEdit_title.text()
        msg = self.msgbox.toPlainText()
        print(to_addr + " " + title + " " + msg)
        if len(to_addr) == 0 or len(title) == 0:
            self.label_4.setText("收件人和主题不能为空！！！")
        else:
            smtp = Smtp()
            smtp.loginsmtp()
            if self.filename is None:
                smtp.sendmsg(msg, title, to_addr)
                self.label_4.setText("<"+title+">"+"发送成功！！！")
                smtp.srv.quit()
            else:
                smtp.sendwithfile(msg, title, self.filepath, self.filename, to_addr)
                self.label_4.setText("<"+title+">"+"发送成功！！！")
                smtp.srv.quit()

    def addfile(self):
        file=QFileDialog.getOpenFileName()
        self.filepath = file[0]
        self.filename = os.path.basename(self.filepath)
        self.label_5.setText("附件:"+self.filepath)
        self.label_4.setText("附件添加成功！！！")
        print(self.filepath)
        print(self.filename)
